DRMS/app/views/admin.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'zhuhuijie'
__email__ = "zhuhuijie@cnnic.cn"
__copyright__ = "Copyright 2014,Cnnic"
__version__ = "1.0.0"
__deprecated__ = False
__date__ = "2014-09-18"
from flask import Blueprint, redirect, url_for, render_template, request,flash
from app.forms.admin import LoginForm
from epp_client.interaction import receive_xml

admin = Blueprint('admin', __name__)


@admin.route('/', methods=("GET", "POST"))
def admin_sin():
    form = LoginForm()
    if request.method == 'POST':
        clID = request.form['admin']
        pw = request.form['password']
        print clID,pw
        req_xml = {"session":{"login":{"clID":clID,"pw":pw}}}
        print req_xml
        rsp = receive_xml(req_xml)
        print rsp
        if rsp['attrib']['code'] == '1000':
            flash(u'登陆成功')
            return redirect(url_for('site.index'))
        else:
            flash(u'登陆失败')
            return render_template('/admin/admin.html',form=form)
    
    return render_template('/admin/admin.html',form=form)

DRMS/app/views/domain.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
    the domain manage view
"""
__author__ = 'zhuhuijie'
__email__ = "zhuhuijie@cnnic.cn"
__copyright__ = "Copyright 2014,Cnnic"
__version__ = "1.0.0"
__deprecated__ = False
__date__ = "2014-09-18"

from flask import Blueprint,Module,render_template,request, redirect, url_for, flash
from flask.ext.login import login_required,current_user
from app.models import ResolveType,DnsInfo,Domain,DomainData
from app.extensions import db
from app.utils.interface import query_audit_status
from epp_client.interaction import receive_xml
from sqlalchemy import and_
import os, sys
from datetime import  datetime,timedelta


domain = Blueprint('domain', __name__)



@domain.route('/list', methods=("GET", "POST"))
@login_required
def domain_list():

    user_id = current_user.user.id
    domain_list = Domain.query.filter(Domain.user_id == user_id).all()

    return render_template('/domain/domain_list.html', domain_list=domain_list)

@domain.route('/show', methods=("GET", "POST"))
@login_required
def domain_show():
    """
       show the one domain detail
    """
    domain_code = request.args.get('domain_code')
    print domain_code
    if domain_code:
        print domain_code
        domain = Domain.query.filter(Domain.domain_code == domain_code).first()
        print domain.create_duration
        disable_time = domain.create_time + timedelta(days=int(domain.create_duration)*365)
        print disable_time
        print domain.domain_data.contact
        return render_template('/domain/domain_show.html', domain=domain,disable_time=disable_time)


@domain.route('/detail', methods=("GET", "POST"))
@login_required
def domain_detail():
    """
       show the one domain detail
    """
    domain_code = request.args.get('domain_code')
    if domain_code:
        print domain_code
        domain = Domain.query.filter(Domain.domain_code == domain_code).first()
        print domain.domain_data.contact
        return render_template('/domain/domain_detail.html', domain=domain)



@domain.route('/dns_update', methods=("GET", "POST"))
@login_required
def dns_update():
    """
        domain dns update
    """
    id = request.args.get('id', None)
    if id:
        dns = DnsInfo.query.get(id)

    next = request.args.get('next', None)

    if request.method == 'POST':
        dns.url = request.form['url']
        dns.resolve_type_id = request.form['resolve_type']
        db.session.merge(dns)

        req_xml = {
            "domain": {
                "update": {
                    "name": dns.domain_name,
                    "chg": {
                        "record": {
                            "type": dns.resolve_type_id,
                            'url': dns.url
                        }
                    }
                }
            }
        }
        print req_xml
        rsp = receive_xml(req_xml)
        print rsp
        if rsp['attrib']['code'] == '1000':
            flash(u'域名解析成功')
            return redirect(url_for('domain.dns_list'))
        else:
            flash(u'域名解析失败')
            types = ResolveType.query.filter().all()
            return render_template('/domain/domain_resolve.html', dns=dns, domain_name=dns.domain_name, next=next, types=types,title=u'域名解析更新')
    else:
        flash(u'存在解析记录')
        types = ResolveType.query.filter().all()
        return render_template('/domain/domain_resolve.html', dns=dns, domain_name=dns.domain_name, next=next, types=types,title=u'域名解析更新')

@domain.route('/dns_save', methods=("GET", "POST"))
@login_required
def dns_save():
    """
        domain name resolve add
    """
    domain_code = request.args.get('domain_code', None)
    domain_name = domain_code + '.niot.cn'

    if domain_name:
        dns = DnsInfo.query.filter(DnsInfo.domain_name == domain_name).first()
        if dns:

            return redirect(url_for('domain.dns_update', id=dns.id, next=url_for('domain.domain_show',domain_code=domain_code)))

    if request.method == 'POST':
        dns = DnsInfo()
        dns.domain_name = domain_name
        dns.url = request.form['url']
        dns.resolve_type_id = request.form['resolve_type']
        req_xml = {
            "domain": {
                "update": {
                    "name": dns.domain_name,
                    "chg": {
                        "record": {
                            "type": dns.resolve_type_id,
                            'url': dns.url
                        }
                    }
                }
            }
        }
        rsp = receive_xml(req_xml)
        print rsp
        if rsp['attrib']['code'] == '1000':
            db.session.add(dns)
            flash(u'域名解析成功')
        return redirect(url_for('domain.domain_show'))
    else:

        types = ResolveType.query.filter().all()
        return render_template('/domain/domain_resolve.html', domain_name=domain_name, next=url_for('domain.domain_show',domain_code=domain_code), types=types,title=u'域名解析添加')


@domain.route('/dns_list', methods=("GET", "POST"))
@login_required
def dns_list():
    """
        list the login user's all domain's dns
    """
    domain_names = ['1234657890123.niot.cn']
    dns = DnsInfo.query.filter(and_(DnsInfo.status == '1', DnsInfo.domain_name.in_(domain_names))).all()
    return render_template('/domain/domain_resolve_list.html', dns=dns)

@domain.route('/dns_del', methods=("GET", "POST"))
@login_required
def dns_delete():
    """
        delete one domain's dns
    """
    id = request.args.get('id')
    if id:
        print id
        dns = DnsInfo.query.get(id)
        dns.status = '0'
    return redirect(url_for('domain.dns_list'))

@domain.route('/query_status', methods=("GET", "POST"))
@login_required
def query_status():
    """
        query the domain's audit status by webservice interface
    """
    domain_code = request.args.get('domain_code')
    domain_name = domain_code + '.niot.cn'
    domain = Domain.query.filter(Domain.domain_code == domain_code).first()
    result = query_audit_status(domain_name)
    print result
    if result[0] == 1:
        print "ok"
        return render_template('/domain/domain_show.html', status=result[2], domain=domain)
    else:
        flash('%s' % result[1])
        print result[1]
        return redirect(url_for('domain.domain_show',domain_code=domain_code))

DRMS/app/views/site.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'zhuhuijie'
__email__ = "zhuhuijie@cnnic.cn"
__copyright__ = "Copyright 2014,Cnnic"
__version__ = "1.0.0"
__deprecated__ = False
__date__ = "2014-09-18"

from flask import render_template,Blueprint
site = Blueprint("site", __name__)

@site.route('/')
def index():
    return  render_template('index.html')

DRMS/app/views/user.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'zhuhuijie'
__email__ = "zhuhuijie@cnnic.cn"
__copyright__ = "Copyright 2014,Cnnic"
__version__ = "1.0.0"
__deprecated__ = False
__date__ = "2014-09-18"
from flask import Blueprint, redirect, url_for, render_template, request,flash,session,current_app
from flask.ext.login import current_user
from app.extensions import db,login_manager
from flask.ext import login
from flask.ext.login import login_user, login_required
from app.models import User,UserInfo, authenticate
from app.forms.user import SignupForm,LoginForm, EditPassForm
user = Blueprint('user', __name__)

class Anonymous(login.AnonymousUserMixin):
    user = User(nickname=u'游客', email='')

class LoginUser(login.UserMixin):
    """Wraps User object for Flask-Login"""

    def __init__(self, user):
        self.id = user.id
        self.user = user

login_manager.anonymous_user = Anonymous
login_manager.login_view = 'user.signin'
login_manager.login_message = u'需要登陆后才能访问本页'

@login_manager.user_loader
def load_user(user_id):
    user = User.query.get(user_id)
    return user and LoginUser(user) or None

@user.route("/login/", methods=("GET","POST"))
def signin():

    flag = request.args.get('flag')

    if current_user.is_authenticated():
        if flag:
            return redirect(url_for('admin.index'))
        return redirect(url_for('site.index'))

    form = LoginForm(login=request.args.get('login',None),
                     next=request.args.get('next',None))
    if form.validate_on_submit():
        user, authenticated = authenticate(form.email.data,
                                                      form.password.data)
        if user and authenticated:
            # session.permanent = form.remember.data
            remberme = form.remember.data
            # identity_changed.send(current_app._get_current_object(),
            #                       identity=Identity(user.id))
            login_user(user, remberme)

            next_url = form.next.data
            user.is_login = 1

            if not next_url or next_url == request.path:
                if flag:
                    next_url = url_for('admin.index', username=user.nickname)
                else:
                    next_url = url_for('site.index', username=user.nickname)
            return redirect(next_url)

        else:
            pass
            # flash(_("Sorry, invalid login"), "error")
    return render_template("user/signin.html", form=form, flag=flag)



@user.route('/edit_pass', methods=("GET","POST"))
@login_required
def edit_pass():
    form = EditPassForm(next=request.args.get('next',None))
    print request.path
    print form.next.data
    if form.validate_on_submit():
        print "*"*50

        print current_user.user.password
        current_user.user._set_password(form.password.data)
        print current_user.user.password
        print "*"*50
        flash(u'用户密码已经更新', 'success')
        # return form.redirect("user.edit_pass")
        return redirect(url_for('site.index'))
    else:
        # form.errors and flash(u'用户密码未能更新', 'error')
        return render_template('user/edit_pass.html', form=form)

@user.route('/logout')
@login_required
def signout():

    privilege = current_user.user.privilege

    user = User.query.get(current_user.user.id)
    user.is_login = 0
    print privilege
    if privilege == 3:
        to_url = url_for('site.index')
    elif privilege == 4:
        print "---------"
        to_url = url_for('admin.index')
    login.logout_user()

    return redirect(to_url)


@user.route('/signup/', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated():
        return redirect(url_for('site.index'))

    form = SignupForm(request.values, csrf_enabled=False)

    if form.validate_on_submit():
        user = User()
        form.populate_obj(user)
        user.info = UserInfo()
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user.signin'))
    else:
        print "signup"
        return render_template('user/signup.html', form=form)

DRMS/app/templates/_helpers.html
{% macro script_tag(filename) -%}
<script type="text/javascript" src="{{ url_for('static', filename='' ~ filename , _external=true) }}"></script>
{%- endmacro %}

{%- macro style_tag(filename) -%}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='' ~ filename , _external=true) }}" />
{%- endmacro %}

DRMS/app/templates/base.html
<!DOCTYPE html>
{% import '_helpers.html' as tags %}
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>{% block title %}{% endblock %} - ScriptFan.com</title>

        <!-- 全局样式 -->
        {{ tags.style_tag('lib/bootstrap/css/bootstrap.min.css') }}
        {{ tags.style_tag('css/styles.css') }}

        <!-- 页面样式 -->
        {% block styles %}{% endblock %}

        <!-- 全局脚本 -->
        {{ tags.script_tag('lib/jquery-1.7.2.min.js') }}
        {{ tags.script_tag('lib/bootstrap/js/bootstrap.min.js') }}
        {{ tags.script_tag('lib/bootstrap.bform.js') }}
        {{ tags.script_tag('js/application.js') }}

        <!-- 页面脚本 -->
        {% block scripts %}{% endblock %}
    </head>
<body>
          <div  class="navbar navbar-default" role="navigation">
            <div class="container">
                <a class="navbar-brand" href="{{url_for('site.index')}}">CNNIC</a>
                <ul class="nav navbar-nav">
                    <li class="reg">
                        <a href="{{url_for('reg.domain_search')}}">条码注册</a>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            域名管理
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{url_for('domain.domain_list')}}">我的域名</a></li>
                        </ul>
                    </li>
                    {% if current_user.is_authenticated() %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> {{ current_user.user.nickname | default('Account') }}&nbsp;您好！<b class="caret"></b></a>

                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('user.edit_pass', next=url_for('site.index')) }}"><i class="icon icon-user"></i> 修改密码</a></li>
                            <li><a href="{{ url_for('user.signout') }}"><i class="icon icon-off"></i> 退出</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{{ url_for('user.signup') }}">注册</a></li>
                    <li><a href="{{ url_for('user.signin') }}">登陆</a></li>
                    {% endif %}

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{url_for('admin.admin_sin')}}">注册商登陆</a>
                    </li>
                </ul>
            </div>

          </div>
        <div class="container">
            <div class="alert-messages">
                {% for category, message in  get_flashed_messages(with_categories=true) %}
                <div class="alert alert-{{ category | default('info') }}">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    {{ message }}
                </div>
                {% endfor %}
            </div>

            {% block content %}{% endblock %}
            <div class="footer">{% block footer %}{% endblock %}</div>
        </div>
</body>
</html>

DRMS/app/templates/index.html
{% extends "base.html" %}

{% block title %}首页面{% endblock %}

{% block content %}
<div class="container" ><h1><p class="text-center">欢迎页面.</p></h1></div>
{% endblock %}