DRMS/app/forms/reg.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'zhuhuijie'
__email__ = "zhuhuijie@cnnic.cn"
__copyright__ = "Copyright 2014,Cnnic"
__version__ = "1.0.0"
__deprecated__ = False
__date__ = "2014-09-22"
from flask.ext.wtf import Form
from wtforms import TextAreaField, HiddenField, BooleanField, FileField,\
        PasswordField, SubmitField, StringField, ValidationError,validators
from wtforms.validators import DataRequired, Email, EqualTo, Length


# class Search(Form):
#     search = StringField(validators = [DataRequired(message = u'请输入查询的条码'),Length(min=13, max=13, message=u'条码长度必须为13位')])


class RegForm(Form):
    code = StringField(u'商品条码:')
    Time_y = StringField(u'服务年限:/年',validators=[DataRequired(message = u'请输入服务时限,以年为单位')])
    prove = FileField(u'请上传条码证书')



class Cont(Form):
    code = StringField(u'商品条码:')
    comp = StringField(u'条码所有单位',validators=[DataRequired(message=u'请输入公司全称')])
    address = StringField(u'通讯地址:xx市xx街xx楼xx室',validators=[DataRequired(message=u'请输入详细地址:xx市xx街xx楼xx室')])
    comp_http = StringField(u'公司网站',validators=[DataRequired(message=u'公司网址')])
    contact = StringField(u'联系人',validators=[DataRequired(message=u'请输入联系人')])
    pno = StringField(u'联系电话:01012345678',validators =[DataRequired(message = u'请输入电话号码'),Length(min=8,max=11,message='请输入正确的电话号码')])
    mno = StringField(u'手机:13566668888',validators=[DataRequired(message=u'请输入手机号码'),Length(min=11,max=13,message='请输入正确的电话号码')])
    email = StringField('email:1221@123.com', validators=[DataRequired(message=u'请填写电子邮件'),Email(message=u'无效的电子邮件')])
    image = FileField(u"上传营业执照")

DRMS/app/views/reg.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from flask import render_template, Blueprint, request, redirect, flash, url_for
from flask.ext.login import current_user, login_required
from app.forms.reg import  Cont,RegForm
from app.models.db_reg import Domain, DomainData
from app.extensions import db, photos
from app.utils.interface import upload_product_info,upload_data
import uuid
import base64
from datetime import datetime,timedelta
from epp_client.interaction import receive_xml
import os,sys

reg = Blueprint("reg", __name__)
   
@reg.route('/', methods=("GET", "POST"))
@reg.route('/search',methods=("GET", "POST"))
@login_required
def domain_search():
    if request.method =='POST':
        name = request.form['code']
        if name.isdigit() and len(name) == 13:
            req_xml = {"domain":{"check":{"name":name}}}
            rsp = receive_xml(req_xml)
            if rsp['attrib']['code'] == '1000':
                if rsp['attrib']['avail'] == '0':
                    flash(u"该条码已注册")
                    return render_template('/reg/search.html')
                if rsp['attrib']['avail'] == '1':
                    flash(u"该条码未注册")
                    result = u'未注册'
                    return render_template('/reg/search.html',code=name,result=result)
            else:
                flash(u"系统连接错误")
                return redirect(url_for('site.index'))

        else:

            flash(u"该条码必须是13位数字")
            return render_template('/reg/search.html')
    return render_template('/reg/search.html')


@reg.route('/reg', methods=("GET", "POST"))
@login_required
def domain_reg():
    codes =  request.args.get('codes')
    contact = current_user.user.email
    contact_check = {"contact":{"check":{"id":contact}}}
    rp = receive_xml(contact_check)
    if rp["attrib"]['code'] == '1000':
        if rp["attrib"]['avail'] == '1':
            form = RegForm(code=codes)
            if request.method == 'POST':
                names = request.form['code']
                period = request.form['Time_y']
                req_xml = {
                    "domain":{
                        "create":{
                            "name":names,
                            "period":period,
                            "hostObj":"2.cnnic.com",
                            "registrant":"ClientX",
                            "contact":contact
                            }
                        }
                    }
                rsp = receive_xml(req_xml)
                if rsp['attrib']['code'] == '1000':
                    domain_pro = Domain()
                    domain_pro.domain_code = names
                    domain_pro.create_time = datetime.now()
                    domain_pro.create_duration = request.form['Time_y']
                    f = DomainData.query.filter(DomainData.user_id == current_user.id).first().id
                    print f,"=============+++++++++++++++"
                    domain_pro.domain_data_id = f
                    #domain_pro.modified_time = datetime.now()
                    domain_pro.user_id = current_user.id

                    # file_prove = request.files['prove']
                    # file_prove_name = str(uuid.uuid4()) + ".jpg"
                    # photos.save(file_prove,name = file_prove_name)
                    # url_prove = photos.url(file_prove_name)
                    # domain_pro.prove = url_prove 
                    p = Domain.query.filter(Domain.domain_code == domain_pro.domain_code).first()
                    if p is None:
                        db.session.add(domain_pro)
                    else:
                        db.session.merge(domain_pro)

                    # fpath = photos.path(file_prove_name)
                    # f = open(fpath,'rb')
                    # fdata = base64.b64encode(f.read())
                    # domain_name = form.code.data
                    # res1 = upload_data(domain_name,fdata)
           
                    # if res1[0] == 1:
                    #     flash(u'资料上传成功')
                    # else:
                    #     flash(u'资料上传失败 原因: %s' % res1[1])
                    #     render_template('/reg/reg.html',form=form)

                    flash(u'域名注册成功')
                    return redirect(url_for('site.index'))
                else:
                    flash(u'域名注册失败')
                    return render_template('/reg/reg.html',form=form)
            else:
                return render_template('/reg/reg.html',form=form)
        if rp["attrib"]['avail'] == '0':
            flash(u'请先创建注册信息')
            return redirect(url_for('reg.domian_con',codes = codes))
    else:
        flash(u'系统错误')
        return render_template('/reg/search.html')

    return render_template('/reg/reg.html',form=form)

@reg.route('/con',methods=("GET", "POST"))
@login_required
def domian_con():
    codes =  request.args.get('codes')
    form = Cont()
    if request.method == 'POST':
        comp = form.comp.data
        address = form.address.data
        contact = form.contact.data
        pno = form.pno.data
        mno = form.mno.data
        email = form.email.data
        user_id = current_user.user.email
        req_xml = {
            "contact":{
                "create":{
                    "id":user_id,
                    "name":contact,
                    "street":address,
                    "voice":pno,
                    "fax":mno,
                    "email":email,
                    "cc":"cn",
                    "city":"beijing",
                    "sp":"VA",
                    "pc":"20166-6503"
                    }
                }
            }
        rsp = receive_xml(req_xml)
        if rsp['attrib']['code'] == '1000':
            data_pro = DomainData()
            data_pro.comp = comp
            data_pro.address = address
            data_pro.contact = contact
            data_pro.pno = pno
            data_pro.mno = mno
            data_pro.email = email
            data_pro.user_id = current_user.id
            # files_image = request.files['image']
            # files_image_name = str(uuid.uuid4()) + '.jpg'
            # photos.save(files_image,name = files_image_name)
            # url_image = photos.url(files_image_name)
            # data_pro.image = url_image
            p = DomainData.query.filter(DomainData.user_id == data_pro.user_id).first()
            if p is None:
                db.session.add(data_pro)
            else:
                db.session.merge(data_pro)

            # fpath = photos.path(files_image_name)
            # f = open(fpath,'rb')
            # fdata = base64.b64encode(f.read())
            # domain_name = codes
            # print domain_name,"&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
            # res1 = upload_data(domain_name,fdata)
   
            # if res1[0] == 1:
            #     flash(u'资料上传成功')
            # else:
            #     flash(u'资料上传失败 原因: %s' % res1[1])
            #     render_template('/reg/con.html',form=form)
            
            flash(u'信息添加成功,现在可进行域名注册')
            print codes,"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
            return redirect(url_for('reg.domain_search',code = codes))

        else:
            flash(u'信息已存在,请勿重复添加')
            print codes,"--------------------------------------------------------------"
            #return render_template('/reg/reg.html',codes = codes)
            return redirect(url_for('reg.domain_search',codes = codes))
            #return redirect(url_for('site.index'))
    return render_template('/reg/con.html',form=form)

DRMS/app/templates/reg/_con.html
{% extends "base.html" %}
{% block title %}信息创建{% endblock %}
{% block content %}
<div class="content">
    <div class="page-header">
        <h3>信息创建</h3>
    </div>
    <form class="form-horizontal " action="{{url_for('reg.domian_con')}}" method="POST" enctype="multipart/form-data">
        <div class="form-group {{ form.comp | error_class }}">
            <label class="col-sm-2 control-label">{{ form.comp.label }}</label>
            <div class="col-sm-10">
                {{ form.comp }}
                <span class="help-inline">{{ form.comp | error_text }}</span>
            </div>
        </div>

        <div class="form-group {{ form.address | error_class }}">
            <label class="col-sm-2 control-label">{{ form.address.label }}</label>
            <div class="col-sm-10">
                {{ form.address }}
                <span class="help-inline">{{ form.address | error_text }}</span>
            </div>
        </div>

       <div class="form-group {{ form.contact | error_class }}">
            <label class="col-sm-2 control-label">{{ form.contact.label }}</label>
            <div class="col-sm-10">
                {{ form.contact }}
                <span class="help-inline">{{ form.contact | error_text }}</span>
            </div>
        </div>
        <div class="form-group {{ form.pno | error_class }}">
             <label class="col-sm-2 control-label">{{ form.pno.label }}</label>
             <div class="col-sm-10">
                 {{ form.pno }}
                 <span class="help-inline">{{ form.pno | error_text }}</span>
             </div>
         </div>
         <div class="form-group {{ form.mno | error_class }}">
              <label class="col-sm-2 control-label">{{ form.mno.label }}</label>
              <div class="col-sm-10">
                  {{ form.mno }}
                  <span class="help-inline">{{ form.mno | error_text }}</span>
              </div>
          </div>
          <div class="form-group {{ form.email | error_class }}">
               <label class="col-sm-2 control-label">{{ form.email.label }}</label>
               <div class="col-sm-10">
                   {{ form.email }}
                   <span class="help-inline">{{ form.email | error_text }}</span>
               </div>
           </div>
           <!--div class="form-group {{ form.image | error_class }}">
                <label class="col-sm-2 control-label">{{ form.image.label }}</label>
                <div class="col-sm-10">
                    {{ form.image }}
                    <span class="help-inline">{{ form.image | error_text }}</span>
                </div>
            </div-->
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">提交</button>
                <a href="{{ url_for('reg.domain_search') }}" class="btn btn-default">返回</a>
            </div>
         </div>
    </form>
</div>
{% endblock %}

DRMS/app/templates/reg/reg.html
{% extends "base.html" %}
{% block title %}条码注册{% endblock %}
{% block content %}
<div class="content">
    <div class="page-header">
        <h3>条码注册</h3>
    </div>
    <form class="form-horizontal " action="{{url_for('reg.domain_reg')}}" method="POST" enctype="multipart/form-data" >
        <div class="form-group {{ form.code | error_class }}">
            <label class="col-sm-2 control-label">{{ form.code.label }}</label>
            <div  class="col-sm-10">
                {{ form.code }}
                <span class="help-inline">

                </span>
            </div>
        </div>
        
        <div class="form-group {{ form.Time_y | error_class }}">
            <label class="col-sm-2 control-label">{{ form.Time_y.label }}</label>
            <div class="col-sm-10">
                {{ form.Time_y }}
                <span class="help-inline">{{ form.Time_y | error_text }}</span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">下一步</button>
                <a href="{{ url_for('reg.domain_search') }}" class="btn btn-default">返回</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

DRMS/app/templates/reg/search.html
{% extends "base.html" %}
{% block title %}商品信息{% endblock %}
{% block scripts %}


 {% endblock %}
{% block content %}

    <div class="col-md-10">
        <form method="POST" action="{{ url_for('reg.domain_search') }}">
            <div class="col-md-6">
                <input class="form-control" placeholder="请输入要查询的条码" name="code" value="{{code}}">
                <div class="help-block">
                    <em>条码为13个数字</em>
                </div>
            </div>
            <div class="col-md-1">
                <button class="btn btn-primary " type="submit">查询</button>
            </div>
            {% if result%}
            <div class="col-md-2">
                <a href="{{url_for('reg.domain_reg',codes = code)}}" class = "btn btn-default">注册</a>
            </div>
          {%endif%}
        </form>
        
    </div>


{% endblock %}