DRMS/app/models/domain.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'zhuhuijie'
__email__ = "zhuhuijie@cnnic.cn"
__copyright__ = "Copyright 2014,Cnnic"
__version__ = "1.0.0"
__deprecated__ = False
__date__ = "2014-09-24"

from app.extensions import db
from datetime import datetime

class ResolveType(db.Model):
    """
        resolve_type orm table
    """
    __tablename__ = "resolve_type"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(10))
    dns = db.relationship('DnsInfo', backref='type', uselist=False)


class DnsInfo(db.Model):
    """
      dns info orm
    """
    __tablename__ = 'dns_info'
    id = db.Column(db.Integer, primary_key=True)
    domain_name = db.Column(db.String(32))
    resolve_type_id = db.Column(db.Integer, db.ForeignKey('resolve_type.id'), nullable=False)
    url = db.Column(db.String(50))
    status = db.Column(db.String(1))

DRMS/app/forms/domain.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'zhuhuijie'
__email__ = "zhuhuijie@cnnic.cn"
__copyright__ = "Copyright 2014,Cnnic"
__version__ = "1.0.0"
__deprecated__ = False
__date__ = "2014-09-23"

from flask.ext.wtf import Form
from wtforms import SelectField, HiddenField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length, NumberRange,Regexp
from app.models import ResolveType

DRMS/app/views/domain.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
    the domain manage view
"""
__author__ = 'zhuhuijie'
__email__ = "zhuhuijie@cnnic.cn"
__copyright__ = "Copyright 2014,Cnnic"
__version__ = "1.0.0"
__deprecated__ = False
__date__ = "2014-09-18"

from flask import Blueprint,Module,render_template,request, redirect, url_for, flash
from flask.ext.login import login_required,current_user
from app.models import ResolveType,DnsInfo,Domain,DomainData
from app.extensions import db
from app.utils.interface import query_audit_status
from epp_client.interaction import receive_xml
from sqlalchemy import and_
import os, sys
from datetime import  datetime,timedelta


domain = Blueprint('domain', __name__)



@domain.route('/list', methods=("GET", "POST"))
@login_required
def domain_list():

    user_id = current_user.user.id
    domain_list = Domain.query.filter(Domain.user_id == user_id).all()

    return render_template('/domain/domain_list.html', domain_list=domain_list)

@domain.route('/show', methods=("GET", "POST"))
@login_required
def domain_show():
    """
       show the one domain detail
    """
    domain_code = request.args.get('domain_code')
    print domain_code
    if domain_code:
        print domain_code
        domain = Domain.query.filter(Domain.domain_code == domain_code).first()
        print domain.create_duration
        disable_time = domain.create_time + timedelta(days=int(domain.create_duration)*365)
        print disable_time
        print domain.domain_data.contact
        return render_template('/domain/domain_show.html', domain=domain,disable_time=disable_time)


@domain.route('/detail', methods=("GET", "POST"))
@login_required
def domain_detail():
    """
       show the one domain detail
    """
    domain_code = request.args.get('domain_code')
    if domain_code:
        print domain_code
        domain = Domain.query.filter(Domain.domain_code == domain_code).first()
        print domain.domain_data.contact
        return render_template('/domain/domain_detail.html', domain=domain)



@domain.route('/dns_update', methods=("GET", "POST"))
@login_required
def dns_update():
    """
        domain dns update
    """
    id = request.args.get('id', None)
    if id:
        dns = DnsInfo.query.get(id)

    next = request.args.get('next', None)

    if request.method == 'POST':
        dns.url = request.form['url']
        dns.resolve_type_id = request.form['resolve_type']
        db.session.merge(dns)

        req_xml = {
            "domain": {
                "update": {
                    "name": dns.domain_name,
                    "chg": {
                        "record": {
                            "type": dns.resolve_type_id,
                            'url': dns.url
                        }
                    }
                }
            }
        }
        print req_xml
        rsp = receive_xml(req_xml)
        print rsp
        if rsp['attrib']['code'] == '1000':
            flash(u'域名解析成功')
            return redirect(url_for('domain.dns_list'))
        else:
            flash(u'域名解析失败')
            types = ResolveType.query.filter().all()
            return render_template('/domain/domain_resolve.html', dns=dns, domain_name=dns.domain_name, next=next, types=types,title=u'域名解析更新')
    else:
        flash(u'存在解析记录')
        types = ResolveType.query.filter().all()
        return render_template('/domain/domain_resolve.html', dns=dns, domain_name=dns.domain_name, next=next, types=types,title=u'域名解析更新')

@domain.route('/dns_save', methods=("GET", "POST"))
@login_required
def dns_save():
    """
        domain name resolve add
    """
    domain_code = request.args.get('domain_code', None)
    domain_name = domain_code + '.niot.cn'

    if domain_name:
        dns = DnsInfo.query.filter(DnsInfo.domain_name == domain_name).first()
        if dns:

            return redirect(url_for('domain.dns_update', id=dns.id, next=url_for('domain.domain_show',domain_code=domain_code)))

    if request.method == 'POST':
        dns = DnsInfo()
        dns.domain_name = domain_name
        dns.url = request.form['url']
        dns.resolve_type_id = request.form['resolve_type']
        req_xml = {
            "domain": {
                "update": {
                    "name": dns.domain_name,
                    "chg": {
                        "record": {
                            "type": dns.resolve_type_id,
                            'url': dns.url
                        }
                    }
                }
            }
        }
        rsp = receive_xml(req_xml)
        print rsp
        if rsp['attrib']['code'] == '1000':
            db.session.add(dns)
            flash(u'域名解析成功')
        return redirect(url_for('domain.domain_show'))
    else:

        types = ResolveType.query.filter().all()
        return render_template('/domain/domain_resolve.html', domain_name=domain_name, next=url_for('domain.domain_show',domain_code=domain_code), types=types,title=u'域名解析添加')


@domain.route('/dns_list', methods=("GET", "POST"))
@login_required
def dns_list():
    """
        list the login user's all domain's dns
    """
    domain_names = ['1234657890123.niot.cn']
    dns = DnsInfo.query.filter(and_(DnsInfo.status == '1', DnsInfo.domain_name.in_(domain_names))).all()
    return render_template('/domain/domain_resolve_list.html', dns=dns)

@domain.route('/dns_del', methods=("GET", "POST"))
@login_required
def dns_delete():
    """
        delete one domain's dns
    """
    id = request.args.get('id')
    if id:
        print id
        dns = DnsInfo.query.get(id)
        dns.status = '0'
    return redirect(url_for('domain.dns_list'))

@domain.route('/query_status', methods=("GET", "POST"))
@login_required
def query_status():
    """
        query the domain's audit status by webservice interface
    """
    domain_code = request.args.get('domain_code')
    domain_name = domain_code + '.niot.cn'
    domain = Domain.query.filter(Domain.domain_code == domain_code).first()
    result = query_audit_status(domain_name)
    print result
    if result[0] == 1:
        print "ok"
        return render_template('/domain/domain_show.html', status=result[2], domain=domain)
    else:
        flash('%s' % result[1])
        print result[1]
        return redirect(url_for('domain.domain_show',domain_code=domain_code))

DRMS/app/views/product.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'zhuhuijie'
__email__ = "zhuhuijie@cnnic.cn"
__copyright__ = "Copyright 2014,Cnnic"
__version__ = "1.0.0"
__deprecated__ = False
__date__ = "2014-09-22"

from flask import render_template, Blueprint, request, redirect, flash, url_for
from flask.ext.login import current_user, login_required
from app.forms.product import ProductForm
from app.models.product import ProcutInfo, ImageInfo
from app.extensions import db, photos
from app.utils.interface import upload_product_info
import uuid
import base64

product = Blueprint("product", __name__)




@product.route('/upload', methods=("GET", "POST"))
@login_required
def product_upload():
    #
    print current_user.is_authenticated()
    # if not current_user.is_authenticated():
    #     return redirect(url_for('user.signin'))
    product_code = request.args.get('domain_code')
    product = ProcutInfo.query.filter(ProcutInfo.product_code == product_code).first()
    if product:
        product_form = ProductForm(product_code=product.product_code, product_name=product.product_name,
                                   detail_info=product.detail_info, guide_price=product.guide_price,
                                   introduce=product.introduce, pack_list=product.pack_list,
                                   phone_num=product.phone_num,
                                   csrf_enabled=False)
        form = product_form
        images= product.images
    else:
        form = ProductForm(request.values, csrf_enabled=False)
        images =None
    if form.validate_on_submit():
        product = ProcutInfo()
        form.populate_obj(product)
        file = request.files['product_image']
        filename = str(uuid.uuid4()) + '.jpg'
        photos.save(file, name=filename)
        url = photos.url(filename)
        image = ImageInfo()
        image.name = filename
        image.url = url
        product.images = [image]
        p = ProcutInfo.query.filter(ProcutInfo.product_code == product.product_code).first()
        if p is None:
            db.session.add(product)
        else:
            db.session.merge(product)
        fpath = photos.path(filename)
        f = open(fpath, 'rb')
        fdata = base64.b64encode(f.read())
        rsp = upload_product_info(product, filename, fdata)
        print rsp
        if rsp[0] == 1:
            flash(u'资料上传成功', 'success')
            return redirect(url_for('site.index'))
        else:
            pass
    else:
        return  render_template('/product/info_upload.html', form=form,images=images)

DRMS/app/views/site.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
__author__ = 'zhuhuijie'
__email__ = "zhuhuijie@cnnic.cn"
__copyright__ = "Copyright 2014,Cnnic"
__version__ = "1.0.0"
__deprecated__ = False
__date__ = "2014-09-18"

from flask import render_template,Blueprint
site = Blueprint("site", __name__)

@site.route('/')
def index():
    return  render_template('index.html')

DRMS/app/templates/domain/domain_detail.html
{% extends "base.html" %}
{% block title %}域名详细信息{% endblock %}

{% block content %}
<div class="content">
    <div class="page-header">
        <h3>域名详细信息</h3>
    </div>

    <form class="form-horizontal" action="" method="POST">

        <div class="form-group">
            <label class="col-sm-2 control-label">条码</label>
            <div class="col-sm-10 form-control-static" >
                {{domain.domain_code}}
            </div>
        </div>
         <div class="form-group">
            <label class="col-sm-2 control-label">申请时间</label>
            <div class="col-sm-10 form-control-static">
                {{domain.create_time}}
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">服务时长</label>
            <div class="col-sm-10 form-control-static">
                {{domain.create_duration}}
            </div>
        </div>
         <div class="form-group">
            <label class="col-sm-2 control-label">公司名</label>
            <div class="col-sm-10 form-control-static">
               <input value="{{domain.domain_data.comp}}"/>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">公司地址</label>
            <div class="col-sm-10 form-control-static">
                <input value="{{domain.domain_data.address}}"/>
            </div>
        </div>
     {#
        <div class="form-group">
            <label class="col-sm-2 control-label">公司网站</label>
            <div class="col-sm-10 form-control-static">
                <input value="{{domain.domain_data.comp_http}}"/>

            </div>
        </div>
     #}
        <div class="form-group">
            <label class="col-sm-2 control-label">联系人</label>
            <div class="col-sm-10 form-control-static">
                <input value="{{domain.domain_data.contact}}"/>

            </div>
        </div>
         <div class="form-group">
            <label class="col-sm-2 control-label">电话</label>
            <div class="col-sm-10 form-control-static">
                <input value="{{domain.domain_data.pno}}"/>

            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">条码证书</label>
            <div class="col-sm-10 form-control-static">
                <img src="{{domain.prove}}" width="400" height="300"/>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">营业执照</label>
            <div class="col-sm-10 form-control-static">
                <img src="{{domain.domain_data.image}}" width="400" height="300"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">重新提交审核</button>
                <a href="{{ url_for('site.index') }}" class="btn btn-default">返回</a>
            </div>
         </div>
    </form>
</div>
{% endblock %}

DRMS/app/templates/domain/domain_list.html
{% extends "base.html" %}
{% block title %}域名管理{% endblock %}
{% block scripts %}

{% endblock %}
{% block content %}

<div class="">

   <table class="table table-bordered table-hover">
      <caption><h3>我的域名</h3></caption>
      <thead>
         <tr>
            <th align="center">域名</th>
            <th>创建时间</th>
            <th>服务时长</th>
            <th>操作</th>
         </tr>
      </thead>
      <tbody>
        {% if domain_list%}
        {% for domain in domain_list%}
         <tr>
            <td>{{domain.domain_code}}.niot.cn</td>
            <td>{{domain.create_time}}</td>
            <td>{{domain.create_duration}}年</td>
            <td>
                <a href="{{url_for('domain.domain_show', domain_code=domain.domain_code )}}" class="btn btn-success" role="button">
                    管理
                </a>
            </td>
         </tr>
        {% endfor%}
        {% endif %}
      </tbody>
   </table>
</div>

{% endblock %}

DRMS/app/templates/domain/domain_resolve.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block scripts %}

{% endblock %}
{% block content %}
<div class="content">
    <div class="page-header">
        <h3>{{title}}</h3>
    </div>
    <form class="form form-horizontal" action="" method="POST">

        <div class="form-group ">
            <label class="col-sm-2 control-label">域名</label>
            <div class="col-sm-10">
                {{domain_name}}
            </div>
        </div>
       <div class="form-group ">
            <label class="col-sm-2 control-label"><label for="resolve_type">解析类型</label></label>
            <div class="col-sm-10">

                <select id="resolve_type" name="resolve_type">
                    {% if types%}
                        {% for type in types%}
                            <option value="{{type.id}}">{{type.name}}</option>
                        {% endfor %}
                    {% endif%}
                </select>
            </div>
       </div>
        {%if dns%}
        <div class="form-group ">
            <label class="col-sm-2 control-label"><label for="url">原解析URL</label></label>
            <div class="col-sm-10">
               {{dns.url}}
            </div>
        </div>
        {% endif %}
        <div class="form-group ">
            <label class="col-sm-2 control-label"><label for="url">解析URL</label></label>
            <div class="col-sm-10">
                <input id="url" name="url" type="text" value="">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">提交</button>
            <a href="{{ next }}" class="btn btn-default">返回</a>
            </div>
         </div>

    </form>
</div>
{% endblock %}

DRMS/app/templates/domain/domain_resolve_list.html
{% extends "base.html" %}
{% block title %}域名解析{% endblock %}
{% block scripts %}

{% endblock %}
{% block content %}

<div class="">

   <table class="table table-bordered table-hover">
      <caption><h3>域名解析列表</h3></caption>
      <thead>
         <tr>
            <th align="center">域名</th>
            <th>解析类型</th>
            <th>url</th>
            <th>操作</th>
         </tr>
      </thead>
      <tbody>
        {% if dns %}
        {% for item in dns %}
         <tr>
            <td>{{item.domain_name}}</td>
            <td>{{item.type.name}}</td>
            <td>{{item.url}}</td>
            <td>
                <a href="{{url_for('domain.dns_update', id= item.id, next = url_for('domain.dns_list'))}}" class="btn btn-primary btn-sm" role="button">
                    修改
                </a>
                <a href="{{url_for('domain.dns_delete', id = item.id)}}" class="btn btn-danger btn-sm" role="button">
                    删除
                </a>
            </td>
         </tr>
        {% endfor %}
      {% endif %}
      </tbody>
   </table>
</div>

{% endblock %}

DRMS/app/templates/domain/domain_show.html
{% extends "base.html" %}
{% block title %}域名管理{% endblock %}
{% block scripts %}
   <script>
       $(function () { $('.popover-hide').popover('hide');});
   </script>

{% endblock %}
{% block content %}

   <div class="panel panel-primary">
   <div class="panel-heading">
      <h3 class="panel-title">域名信息</h3>
   </div>

   <table class="table table-bordered table-hover">
      {% if domain%}
      <tr><td>域名</td><td colspan="3">{{domain.domain_code}}.niot.cn</td></tr>
      <tr><td>创建时间</td><td>{{domain.create_time}}</td><td>到期时间</td><td>{{disable_time}}</td></tr>
      <tr><td>联系人</td><td colspan="3">{{domain.domain_data.contact}}</td></tr>
       <tr><td>资料审核状态</td>
          <td colspan="3">
              {%if status %}
                    {%if status.audit_status =='1' %}
                        审核中
                    {%elif status.audit_status == '2' %}
                        审核通过
                    {%elif status.audit_status == '3' %}
                            <span>审核失败</span>

                           <button type="button" class="btn btn-default popover-hide"
                                title="失败原因" data-container="body"
                                data-toggle="popover" data-placement="top"
                                data-content="{{status.reason}}">
                                点击查看原因
                           </button>
                    {%endif%}
              {%endif%}
              <a href="{{url_for('domain.query_status', domain_code=domain.domain_code )}}" >查看</a>
          </td>
       </tr>
      {% endif %}
   </table>
   <div class="panel-footer">

       <a href="{{url_for('domain.domain_detail', domain_code = domain.domain_code)}}" class="btn btn-default" role="button">查看注册资料</a>
       <a href="{{url_for('product.product_upload', domain_code = domain.domain_code)}}" class="btn btn-default" role="button">查看商品信息</a>
       <a href="{{url_for('domain.dns_save', domain_code = domain.domain_code)}}" class="btn btn-default" role="button">域名解析</a>
   </div>
</div>
{% endblock %}